<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Markup\**" />
	  <Compile Remove="Windows\**" />
	  <EmbeddedResource Remove="Markup\**" />
	  <EmbeddedResource Remove="Windows\**" />
	  <None Remove="Markup\**" />
	  <None Remove="Windows\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Core\Data\LinkedHashCollection.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="sync.ffs_db" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Lib.Harmony" Version="2.3.6" />
		<PackageReference Include="Nebulae.RimWorld" Version="1.5.10" />
	</ItemGroup>

</Project>
